FileVersion = 1

[Project]
Name = "farmhash-beef"
DefaultNamespace = "farmhash"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\debug\\farmhash-c.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\release\\farmhash-c.lib"]
