FileVersion = 1

[Project]
Name = "farmhash-beef"
DefaultNamespace = "farmhash"

[Configs.Debug.Win64]
CLibType = "DynamicDebug"
LibPaths = ["$(ProjectDir)\\libs\\windows\\farmhashd.lib"]

[Configs.Release.Win64]
LibPaths = ["$(ProjectDir)\\libs\\windows\\farmhash.lib"]
